import os

AZURE_COGNITIVE_ACCOUNT_NAME=os.getenv("AZURE_COGNITIVE_ACCOUNT_NAME")
AZURE_SEARCH_SERVICE_NAME=os.getenv("AZURE_SEARCH_SERVICE_NAME")
AZURE_SEARCH_INDEX_NAME=os.getenv("AZURE_SEARCH_INDEX_NAME")
AZURE_SEARCH_API_KEY=os.getenv("AZURE_SEARCH_API_KEY")
OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")
AZURE_EMBEDDING_DEPLOYMENT_NAME=os.getenv("AZURE_EMBEDDING_DEPLOYMENT_NAME")
AZURE_CHAT_DEPLOYMENT_NAME=os.getenv("AZURE_CHAT_DEPLOYMENT_NAME")